name: blakenolanbrown
favicon: null
layout_spectrum: 0.7717085920739919
typography_spectrum: 0.8586511560715735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#bb948f'
    - '#69433d'
    - '#b8cfdd'
  brandStrength: 0.5379797958303243
  lightness: 0.9998663188889623
  saturation: 0.671957055805251
  rhythmicContrast: 0.5569148457143456
purpose: []
